steps:
- id: 'ContainerBuild'
  dir: 'containers/atavism'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/atavism:$SHORT_SHA'
  - '.'

- id: ContainerPush
  name: 'gcr.io/cloud-builders/docker'
  dir: 'containers/atavism'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/atavism:$SHORT_SHA'
  waitFor:
  - 'ContainerBuild'

- id: 'HelmLint'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - lint
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism'
  - 'HELM_REPO_NAME=incubator'
  - 'HELM_REPO_URL=https://kubernetes-charts-incubator.storage.googleapis.com '
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor: ['-']

- id: 'HelmDeps'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - dependency
  - update
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism'
  - 'HELM_REPO_NAME=incubator'
  - 'HELM_REPO_URL=https://kubernetes-charts-incubator.storage.googleapis.com '
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor: ['-']

- id: 'HelmTest'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - test
  - '.'
  - '--cleanup'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism'
  - 'HELM_REPO_NAME=incubator'
  - 'HELM_REPO_URL=https://kubernetes-charts-incubator.storage.googleapis.com '
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmLint'
  - 'HelmDeps'


- id: 'HelmPackage'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - package
  - '--version'
  - '1.0.0-$REVISION_ID-$SHORT_SHA'
  - '.'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism'
  - 'HELM_REPO_NAME=incubator'
  - 'HELM_REPO_URL=https://kubernetes-charts-incubator.storage.googleapis.com '
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmTest'

- id: 'HelmPush'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - gcs
  - push
  - 'atavism-1.0.0-$REVISION_ID-$SHORT_SHA.tar.gz'
  - '--retry'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism'
  - 'HELM_REPO_NAME=bobsh'
  - 'HELM_REPO_URL=gs://bobsh/charts'
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmPackage'


