steps:
- id: 'ContainerBuild'
  dir: 'containers/atavism'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/atavism:$SHORT_SHA'
  - '.'

- id: ContainerPush
  name: 'gcr.io/cloud-builders/docker'
  dir: 'containers/atavism'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/atavism:$SHORT_SHA'
  waitFor:
  - 'ContainerBuild'

- id: 'FixContainerVersion'
  name: 'ubuntu:18.04'
  dir: 'charts/atavism/ourcharts/atavism-service'
  entrypoint: 'sed'
  args:
    - '-i'
    - '-e'
    - 's/latest/$SHORT_SHA/g'
    - 'values.yaml'
  waitFor: ['-']

- id: 'HelmLint'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - lint
  - '--debug'
# Unable to turn this on because of lint issues with mysql chart
#  - '--strict'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-iowa-test'
  - 'HELM_REPO_NAME=incubator'
  - 'HELM_REPO_URL=https://kubernetes-charts-incubator.storage.googleapis.com '
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
    - 'FixContainerVersion'

- id: 'HelmDeps'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - dependency
  - update
  - '--debug'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-iowa-test'
  - 'HELM_REPO_NAME=incubator'
  - 'HELM_REPO_URL=https://kubernetes-charts-incubator.storage.googleapis.com '
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
    - 'FixContainerVersion'

- id: 'HelmPackage'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - package
  - '--debug'
  - '--version'
  - '1.0.0-$SHORT_SHA'
# Need to set this up
#  - '--keyring'
#  - '/foo.gpg'
#  - '--sign'
  - '.'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-iowa-test'
  - 'HELM_REPO_NAME=incubator'
  - 'HELM_REPO_URL=https://kubernetes-charts-incubator.storage.googleapis.com '
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmDeps'
  - 'HelmLint'

- id: 'HelmCanaryRelease'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - install
  - 'atavism-1.0.0-$SHORT_SHA.tgz'
  - '--atomic'
  - '--name=atavism-test-$SHORT_SHA'
  - '--description=CanaryRelease'
  - '--replace'
  - '--debug'
  - '--timeout=1200'
  - '--namespace=atavism-test-$SHORT_SHA'
# Need to sign with pgp first
#  - '--verify'
  - '--wait'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-iowa-test'
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmPackage'

- id: 'HelmCanaryTest'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - test
  - 'atavism-test-$SHORT_SHA'
  - '--cleanup'
  - '--parallel'
  - '--debug'
  - '--timeout=1200'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-iowa-test'
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmCanaryRelease'

- id: 'HelmCanaryDelete'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - delete
  - '--debug'
  - '--purge'
  - 'atavism-test-$SHORT_SHA'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-iowa-test'
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmCanaryTest'

- id: 'HelmCanaryUpgrade'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - upgrade
  - atavism
  - 'atavism-1.0.0-$SHORT_SHA.tgz'
  - '--atomic'
  - '--install'
  - '--debug'
  - '--namespace=atavism'
  - '--timeout=1200'
# Need to sign package with pgp first
#  - '--verify'
  - '--wait'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-london-acceptance'
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmPackage'

- id: 'HelmCanaryUpgradeTest'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - test
  - 'atavism'
  - '--cleanup'
  - '--parallel'
  - '--debug'
  - '--timeout=1200'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-london-acceptance'
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmCanaryUpgrade'

- id: 'HelmGcsPush'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - gcs
  - push
  - 'atavism-1.0.0-$SHORT_SHA.tgz'
  - 'bobsh'
  - '--retry'
  - '--debug'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-iowa-test'
  - 'HELM_REPO_NAME=bobsh'
  - 'HELM_REPO_URL=gs://bob.sh/charts'
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  - 'GCS_PLUGIN_VERSION=0.2.0'
  waitFor:
  - 'HelmCanaryTest'
  - 'HelmCanaryUpgradeTest'


- id: 'HelmProdUpgrade'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - upgrade
  - atavism
  - 'atavism-1.0.0-$SHORT_SHA.tgz'
  - '--atomic'
  - '--install'
  - '--namespace=atavism'
# Need to sign with pgp
#  - '--verify'
  - '--wait'
  - '--timeout=1200'
  - '--debug'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-london-prod'
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmCanaryTest'
  - 'HelmCanaryUpgradeTest'

- id: 'HelmProdUpgradeTest'
  name: 'gcr.io/$PROJECT_ID/helm'
  args:
  - test
  - 'atavism'
  - '--cleanup'
  - '--parallel'
  - '--debug'
  - '--timeout=1200'
  dir: 'charts/atavism'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=atavism-london-prod'
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=kube-system'
  waitFor:
  - 'HelmProdUpgrade'