# Default values for atavism
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

auth:
  type: auth
domain:
  type: domain
login:
  type: login
combat:
  type: combat
instance:
  type: instance
objmgr:
  type: objmgr
wmgr:
  type: wmgr
proxy:
  type: proxy
mob:
  type: mob
arena:
  type: arena
builder:
  type: builder
auction:
  type: auction

atavismdb:
  nameOverride: atavismdb
  fullnameOverride: atavismdb
  mysqlUser: atavism
  mysqlPassword: atavism
  mysqlDatabase: atavism

  persistence:
    size: 8Gi

  resources:
    requests:
      memory: 256M
      cpu: 100m
    limits:
      memory: 256M
      cpu: 100m

masterdb:
  nameOverride: masterdb
  fullnameOverride: masterdb
  mysqlUser: atavism
  mysqlPassword: atavism
  mysqlDatabase: master

  persistence:
    size: 8Gi

  resources:
    requests:
      memory: 256M
      cpu: 100m
    limits:
      memory: 250M
      cpu: 100m

contentdb:
  nameOverride: contentdb
  fullnameOverride: contentdb
  mysqlUser: atavism
  mysqlPassword: atavism
  mysqlDatabase: content

  persistence:
    size: 8Gi

  resources:
    requests:
      memory: 256M
      cpu: 100m
    limits:
      memory: 256M
      cpu: 100m

admindb:
  nameOverride: admindb
  fullnameOverride: admindb
  mysqlUser: atavism
  mysqlPassword: atavism
  mysqlDatabase: atavism

  persistence:
    size: 8Gi

  resources:
    requests:
      memory: 256M
      cpu: 100m
    limits:
      memory: 256M
      cpu: 100m
