# Default values for atavism
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

license:
  email: your@email.org
  key: license-key

auth:
  type: auth
  ports:
    pod:
      - name: mastertcp
        containerPort: 9005
        protocol: TCP
      - name: mastertcp2
        containerPort: 9010
        protocol: TCP
      - name: masterrdp
        containerPort: 9010
        protocol: UDP
      - name: socketpolicy
        containerPort: 5090
        protocol: TCP

    service:
      - name: mastertcp
        port: 9005
        targetPort: 9005
        protocol: TCP
      - name: mastertcp2
        port: 9010
        targetPort: 9010
        protocol: TCP
      - name: masterrdp
        port: 9010
        targetPort: 9010
        protocol: UDP
      - name: socketpolicy
        port: 5090
        targetPort: 5090
        protocol: TCP
  resources:
    requests:
      memory: 262M
      cpu: 35m
    limits:
      memory: 262M
      cpu: 35m

domain:
  type: domain
  ports:
    pod:
      - name: msgsvr
        containerPort: 20377
        protocol: TCP
    service:
      - name: msgsvr
        port: 20377
        targetPort: 20377
        protocol: TCP

login:
  type: login
  ports:
    pod:
      - name: login
        containerPort: 5042
        protocol: TCP
    service:
      - port: 5042
        targetPort: 5042
        protocol: TCP
        name: login

wmgr:
  type: wmgr
  ports:
    pod:
      - name: wmgr
        containerPort: 5042
        protocol: TCP
    service:
      - port: 5042
        targetPort: 5042
        protocol: TCP
        name: wmgr

proxy:
  type: proxy
  ports:
    pod:
      - name: proxy
        containerPort: 5052
        protocol: TCP
      - name: flashpolicy
        containerPort: 5041
        protocol: TCP
      - name: voice
        containerPort: 5067
        protocol: TCP
    service:
      - name: proxy
        port: 5052
        targetPort: 5052
        protocol: TCP
      - name: flashpolicy
        port: 5041
        targetPort: 5041
        protocol: TCP
      - name: voice
        port: 5067
        targetPort: 5067
        protocol: TCP

  resources:
    requests:
      memory: 262M
      cpu: 109m
    limits:
      memory: 262M
      cpu: 109m

objmgr:
  type: objmgr
  ports:
    pod:
      - name: objmgr
        containerPort: 45093
        protocol: TCP
    service:
      - port: 45093
        targetPort: 45093
        protocol: TCP
        name: wmgr

  resources:
    requests:
      memory: 262M
      cpu: 126m
    limits:
      memory: 262M
      cpu: 126m

combat:
  type: combat
instance:
  type: instance

mob:
  type: mob
arena:
  type: arena
builder:
  type: builder
auction:
  type: auction

atavismdb:
  nameOverride: atavismdb
  fullnameOverride: atavismdb
  mysqlUser: atavism
  mysqlPassword: atavism
  mysqlDatabase: atavism

  extraInitContainers: |
    - name: 'copy-init-sql-content'
      image: 'gcr.io/atavism/atavism_server:v2019.1.2'
      command:
      - cp
      - '/opt/atavism_server/sql/New_Install_with_Demo_Data/atavism.sql'
      - '/docker-entrypoint-initdb.d'
      volumeMounts:
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d

  extraVolumes: |
    - name: migrations
      emptyDir: {}

  extraVolumeMounts: |
    - name: migrations
      mountPath: /docker-entrypoint-initdb.d

  persistence:
    size: 8Gi

  resources:
    requests:
      memory: 272M
      cpu: 25m
    limits:
      memory: 272M
      cpu: 25m

masterdb:
  nameOverride: masterdb
  fullnameOverride: masterdb
  mysqlUser: atavism
  mysqlPassword: atavism
  mysqlDatabase: master

  extraInitContainers: |
    - name: 'copy-init-sql-content'
      image: 'gcr.io/atavism/atavism_server:v2019.1.2'
      command:
      - cp
      - '/opt/atavism_server/sql/New_Install_with_Demo_Data/master.sql'
      - '/docker-entrypoint-initdb.d'
      volumeMounts:
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d

  extraVolumes: |
    - name: migrations
      emptyDir: {}

  extraVolumeMounts: |
    - name: migrations
      mountPath: /docker-entrypoint-initdb.d

  persistence:
    size: 8Gi

  resources:
    requests:
      memory: 272M
      cpu: 25m
    limits:
      memory: 272M
      cpu: 25m

contentdb:
  nameOverride: contentdb
  fullnameOverride: contentdb
  mysqlUser: atavism
  mysqlPassword: atavism
  mysqlDatabase: content

  extraInitContainers: |
    - name: 'copy-init-sql-content'
      image: 'gcr.io/atavism/atavism_server:v2019.1.2'
      command:
      - cp
      - '/opt/atavism_server/sql/New_Install_with_Demo_Data/world_content.sql'
      - '/docker-entrypoint-initdb.d'
      volumeMounts:
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d

  extraVolumes: |
    - name: migrations
      emptyDir: {}

  extraVolumeMounts: |
    - name: migrations
      mountPath: /docker-entrypoint-initdb.d

  persistence:
    size: 8Gi

  resources:
    requests:
      memory: 272M
      cpu: 25m
    limits:
      memory: 272M
      cpu: 25m

admindb:
  nameOverride: admindb
  fullnameOverride: admindb
  mysqlUser: atavism
  mysqlPassword: atavism
  mysqlDatabase: admin

  extraInitContainers: |
    - name: 'copy-init-sql-content'
      image: 'gcr.io/atavism/atavism_server:v2019.1.2'
      command:
      - cp
      - '/opt/atavism_server/sql/New_Install_with_Demo_Data/admin.sql'
      - '/docker-entrypoint-initdb.d'
      volumeMounts:
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d

  extraVolumes: |
    - name: migrations
      emptyDir: {}

  extraVolumeMounts: |
    - name: migrations
      mountPath: /docker-entrypoint-initdb.d

  persistence:
    size: 8Gi

  resources:
    requests:
      memory: 272M
      cpu: 25m
    limits:
      memory: 272M
      cpu: 25m