# Default values for atavism
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
license:
  email: your@email.org
  key: license-key

auth:
  type: auth
  ports:
    service:
      type: LoadBalancer
    pod:
      - name: mastertcp
        containerPort: 9005
      - name: masterrdp
        containerPort: 9010
        protocol: UDP
    service:
      - name: mastertcp
        port: 9005
        targetPort: 9005
      - name: masterrdp
        port: 9010
        targetPort: 9010
        protocol: UDP
  resources:
    requests:
      memory: 262M
      cpu: 35m
    limits:
      memory: 262M
      cpu: 35m

domain:
  type: domain
  ports:
    pod:
      - name: msgsvr
        containerPort: 20377
    service:
      - name: msgsvr
        port: 20377
        targetPort: 20377

login:
  type: login

wmgr:
  type: wmgr

proxy:
  type: proxy
  resources:
    requests:
      memory: 262M
      cpu: 109m
    limits:
      memory: 262M
      cpu: 109m

objmgr:
  type: objmgr
  resources:
    requests:
      memory: 262M
      cpu: 126m
    limits:
      memory: 262M
      cpu: 126m

combat:
  type: combat
instance:
  type: instance
mob:
  type: mob
arena:
  type: arena
builder:
  type: builder
auction:
  type: auction

atavismdb: &db
  nameOverride: atavismdb
  fullnameOverride: atavismdb
  mysqlUser: atavism
  mysqlPassword: atavism
  mysqlDatabase: atavism

  extraInitContainers: |
    - name: 'copy-init-sql-content'
      image: 'gcr.io/atavism/atavism_server:v2019.1.2'
      command:
      - cp
      - '/opt/atavism_server/sql/New_Install_Core/atavism.sql'
      - '/docker-entrypoint-initdb.d'
      volumeMounts:
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d

  extraVolumes: |
    - name: migrations
      emptyDir: {}

  extraVolumeMounts: |
    - name: migrations
      mountPath: /docker-entrypoint-initdb.d

  persistence:
    size: 8Gi

  resources:
    requests:
      memory: 272M
      cpu: 25m
    limits:
      memory: 272M
      cpu: 25m

  service:
    type: LoadBalancer

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false

  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 30
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 5

masterdb:
  <<: *db
  nameOverride: masterdb
  fullnameOverride: masterdb
  mysqlDatabase: master

  extraInitContainers: |
    - name: 'copy-init-sql-content'
      image: 'gcr.io/atavism/atavism_server:v2019.1.2'
      command:
      - cp
      - '/opt/atavism_server/sql/New_Install_Core/master.sql'
      - '/docker-entrypoint-initdb.d'
      volumeMounts:
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d


contentdb:
  <<: *db
  nameOverride: contentdb
  fullnameOverride: contentdb
  mysqlDatabase: world_content

  extraInitContainers: |
    - name: 'copy-init-sql-content'
      image: 'gcr.io/atavism/atavism_server:v2019.1.2'
      command:
      - cp
      - '/opt/atavism_server/sql/New_Install_Core/world_content.sql'
      - '/docker-entrypoint-initdb.d'
      volumeMounts:
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d

admindb:
  <<: *db
  nameOverride: admindb
  fullnameOverride: admindb
  mysqlDatabase: admin

  extraInitContainers: |
    - name: 'copy-init-sql-content'
      image: 'gcr.io/atavism/atavism_server:v2019.1.2'
      command:
      - cp
      - '/opt/atavism_server/sql/New_Install_Core/admin.sql'
      - '/docker-entrypoint-initdb.d'
      volumeMounts:
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d

