---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-properties

data:
  auth.properties: |
    atavism.master_tcp_port=9005
    atavism.master_rdp_port=9010
    atavism.socketpolicy.bindport = 5090
    atavism.socketpolicy.bindaddress = auth
    atavism.allowaccountregistration=true
    atavism.db_type=mysql
    atavism.db_driver=com.mysql.jdbc.Driver
    atavism.db_name=master
    atavism.db_user=atavism
    atavism.db_password=atavism
    atavism.db_hostname=masterdb
    atavism.use_salted_passwords=true
    atavism.remote_db_enabled=false
    atavism.remote_db_type=mysql
    atavism.remote_db_driver=com.mysql.jdbc.Driver
    atavism.remote_db_name=admin
    atavism.remote_db_account_table=account
    atavism.remote_db_user=root
    atavism.remote_db_password=test
    atavism.remote_db_hostname=0.0.0.0
    atavism.jdbcJarPath=../other/mysql-connector-java-3.1.14-bin.jar
    atavism.log_level=1
    atavism.rotate_logs_on_startup=true
    #atavism.delete_logs_on_startup=true
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%p\t%d{ISO8601}\t%r\t%c\t[%t]\t%m%n
    log4j.appender.FILE = org.apache.log4j.RollingFileAppender
    log4j.appender.FILE.File = ${atavism.logs}/${atavism.loggername}.out
    log4j.appender.FILE.MaxFileSize = 50MB
    log4j.appender.FILE.MaxBackupIndex=3
    log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
    log4j.appender.FILE.layout.ConversionPattern=%-5p [%d{ISO8601}] %-20t %m%n
    #log4j.appender.ErrorLog = org.apache.log4j.RollingFileAppender
    #log4j.appender.ErrorLog.Threshold = ERROR
    #log4j.appender.ErrorLog.File = ${atavism.logs}/errors.out
    #log4j.appender.ErrorLog.MaxFileSize = 50MB
    #log4j.appender.ErrorLog.MaxBackupIndex=3
    #log4j.appender.ErrorLog.layout=org.apache.log4j.PatternLayout
    #log4j.appender.ErrorLog.layout.ConversionPattern=%-5p [%d{ISO8601}] %-20t %m%n
    log4j.rootLogger=DEBUG, FILE, stdout
    #atavism.use_class_files=true
    atavism.log_rdp_counters=false
    #atavism.cputime_logging_interval=5000,2
    #atavism.message_agent_stats=true
    #atavism.packet_aggregation_interval=0
    atavism.world_available_message = DONE INITIALIZING, you can log in now
  world.properties: |-
    atavism.licence.email={{ .Values.license.email }}
    atavism.licence.key={{ .Values.license.key }}
    atavism.servername=Local
    atavism.login.bindaddress=login
    atavism.login.bindport=5042
    atavism.msgsvr_hostname=domain
    atavism.msgsvr_port=20377
    atavism.worldmgrport=5042
    atavism.proxy.bindaddress=proxy
    atavism.proxy.bindport=5052
    atavism.proxy.externaladdress=proxy
    atavism.voiceserver=:same
    atavism.voiceport=5067
    atavism.flashpolicy.bindport=5041
    atavism.flashpolicy.bindaddress=proxy
    atavism.precreated_positional_voice_group=1
    #atavism.precreated_nonpositional_voice_group=5
    #atavism.autocreate_referenced_voice_groups=true
    #atavism.record_voices=true
    atavism.db_type=mysql
    atavism.db_driver=com.mysql.jdbc.Driver
    atavism.db_name=atavism
    atavism.db_user=atavism
    atavism.db_password=atavism
    atavism.db_hostname=atavismdb
    ### atavism.db_url=jdbc:dbtype://hostName/databaseName
    atavism.admin.db_differentsettings=true
    atavism.admin.db_driver=com.mysql.jdbc.Driver
    atavism.admin.db_name=admin
    atavism.admin.db_user=atavism
    atavism.admin.db_password=atavism
    atavism.admin.db_hostname=adminmdb
    atavism.content.db_differentsettings=true
    atavism.content.db_driver=com.mysql.jdbc.Driver
    atavism.content.db_name=content
    atavism.content.db_user=atavism
    atavism.content.db_password=atavism
    atavism.content.db_hostname=contentdb
    atavism.auth.db_differentsettings=true
    atavism.auth.db_driver=com.mysql.jdbc.Driver
    atavism.auth.db_name=master
    atavism.auth.db_user=atavism
    atavism.auth.db_password=atavism
    atavism.auth.db_hostname=masterdb
    atavism.startup_timeout=120
    atavism.jdbcJarPath=../other/mysql-connector-java-3.1.14-bin.jar
    atavism.service_endpoint=localhost
    atavism.service_user=mgttest
    atavism.service_password=mgttestpass
    atavism.worldname=world
    atavism.log_level=1
    atavism.rotate_logs_on_startup=true
    atavism.archive_logs_on_startup=true
    #atavism.delete_logs_on_startup=true
    log4j.appender.FILE = org.apache.log4j.RollingFileAppender
    log4j.appender.FILE.File = ${atavism.logs}/${atavism.loggername}.out
    log4j.appender.FILE.MaxFileSize = 50MB
    log4j.appender.FILE.MaxBackupIndex=3
    log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
    log4j.appender.FILE.layout.ConversionPattern=%-5p [%d{ISO8601}] %-20t %m%n
    log4j.appender.ErrorLog = org.apache.log4j.RollingFileAppender
    log4j.appender.ErrorLog.Threshold = ERROR
    log4j.appender.ErrorLog.File = ${atavism.logs}/errors.out
    log4j.appender.ErrorLog.MaxFileSize = 50MB
    log4j.appender.ErrorLog.MaxBackupIndex=3
    log4j.appender.ErrorLog.layout=org.apache.log4j.PatternLayout
    log4j.appender.ErrorLog.layout.ConversionPattern=%-5p [%d{ISO8601}] %-20t %m%n
    log4j.rootLogger=DEBUG, FILE
    log4j.rootLogger=DEBUG, FILE, ErrorLog
    #atavism.use_class_files=true
    atavism.log_proxy_histograms=true
    #atavism.log_proxy_histograms_interval=5000
    atavism.log_rdp_counters=false
    atavism.log_voice_counters=true
    #atavism.cputime_logging_interval=5000,2
    #atavism.message_agent_stats=true
    #atavism.packet_aggregation_interval=0
    #atavism.geometry_min_x=-4999999
    #atavism.geometry_max_x=5000000
    #atavism.geometry_min_z=-4999999
    #atavism.geometry_max_z=5000000
    #atavism.quad_tree_node_max_objects=30
    #atavism.quad_tree_max_depth=20
    atavism.world_available_message = \u001B[32mDONE INITIALIZING, you can log in now\u001B[0m
    atavism.plugin_dep.Login=ObjectManager,Instance
    atavism.plugin_dep.Instance=ObjectManager,Quest,MobManager,Inventory,WorldManager
    atavism.plugin_dep.Proxy=Instance
    atavism.plugin_dep.MobManager=ObjectManager,WorldManager,Inventory,Quest,Social
    atavism.plugin_dep.sampleworld.MobManager=ObjectManager,WorldManager,Inventory,Quest,Combat
    atavism.plugin_dep.ObjectManager=
    atavism.plugin_dep.WorldManager=
    atavism.plugin_dep.Inventory=
    atavism.plugin_dep.Quest=
    atavism.plugin_dep.Trainer=
    atavism.plugin_dep.ClassAbility=
    atavism.plugin_dep.Combat=
    atavism.plugin_dep.Vendor=
    atavism.plugin_dep.Domain=Instance,Proxy
    atavism.plugin_dep.DataLogger=
    atavism.plugin_dep.Arena=
    atavism.plugin_dep.Social=
    atavism.plugin_dep.Voxel=
    atavism.plugin_dep.Weather=
    atavism.plugin_dep.Auction=Inventory