{{- template "common.deployment" (list . "workstation.deployment") -}}
{{- define "workstation.deployment" -}}
metadata:
  name: {{ .Values.type }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      hostname: {{ .Values.type }}
      subdomain: {{ .Release.Name }}
      containers:
      - {{ template "common.container" (list . "workstation.deployment.container") }}
      volumes:
      - name: properties-volume
        configMap:
          name: {{ .Release.Name }}-properties
      {{- with .Values.extraVolumes }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | indent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
{{- end -}}

{{- define "workstation.deployment.container" -}}
ports:
{{- with .Values.ports.pod }}
{{ toYaml . }}
{{- end }}
#readinessProbe:
#  tcpSocket:
#    port: 22
#  initialDelaySeconds: 15
#  periodSeconds: 10
#livenessProbe:
#  tcpSocket:
#    port: 22
#  initialDelaySeconds: 15
#  periodSeconds: 20
args: [{{ .Values.type }}]
env:
- name: AUTH_PROPERTYFILE
  value: {{ .Values.atavism.config }}/auth.properties
- name: AO_PROPERTY_FILE
  value: {{ .Values.atavism.config }}/world.properties
volumeMounts:
- name: properties-volume
  mountPath: {{ .Values.atavism.config }}
{{- with .Values.extraVolumeMounts }}
{{ toYaml . }}
{{- end }}
{{- end -}}
