# Type of atavism app server
type: "auth"

atavism:
  config: /etc/atavism

replicaCount: 1

image:
  repository: gcr.io/atavism/atavism
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: 262M
    cpu: 25m
  limits:
    memory: 262M
    cpu: 25m

nodeSelector: {}

tolerations: []

affinity: {}

ports:
  pod: []
  service: []