# Type of atavism app server
type: "auth"

replicaCount: 1

image:
  repository: gcr.io/atavism/atavism
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128M
  requests:
    cpu: 100m
    memory: 128M

nodeSelector: {}

tolerations: []

affinity: {}
